# Generated by Django 5.2.1 on 2025-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Assigned'), ('i', 'In Progress'), ('s', 'Sent'), ('a', 'Approved'), ('o', 'Ordered')], default='p', max_length=20),
        ),
    ]
